In [1]:
import numpy as np

In [2]:
matrix_1 = np.array([
    [0, 3, 4],
    [-7, 1, -2],
    [2, -1, 3]
])

matrix_2 = np.array([
    [1, 2, 4],
    [7, 0, -2],
    [-3, -2, 5]
])

matrix_3 = np.array([
    [-3, 2],
    [0, 4],
    [-1, 7]
])

In [3]:
matrix_12 = matrix_1 @ matrix_2
print(matrix_12)

[[  9  -8  14]
 [  6 -10 -40]
 [-14  -2  25]]


In [4]:
matrix_123 = matrix_12 @ matrix_3
print(matrix_123)

[[ -41   84]
 [  22 -308]
 [  17  139]]


In [5]:
matrix_231 = matrix_1 @ (matrix_2 @ matrix_3)
print(matrix_231)

[[ -41   84]
 [  22 -308]
 [  17  139]]
